### ISSUE TITLE
Invalid Secret

### ISSUE THREAD

**Issue by cwchristerw** [jocic/PHP.GoogleAuthenticator#2]
I want to make sure all kinds of secret are supported but for some reason I cannot use Epic Games style secret like this JVIVET2MKBJUEU2TIZCVORCCJ5GTON2HKNGFOT2FIRCUGT2EIRIQ (this not valid anymore)

**Comment by cwchristerw** [comment]
PHP Error:

Fatal error: Uncaught Exception: Invalid secret provided. Secret: "JVIVET2MKBJUEU2TIZCVORCCJ5GTON2HKNGFOT2FIRCUGT2EIRIQ" in  {FOLDER}/system/external/jocic/google-authenticator/source/Jocic/GoogleAuthenticator/Secret.php:194 Stack trace: #0  {FOLDER}/system/external/jocic/google-authenticator/source/Jocic/GoogleAuthenticator/Secret.php(128): Jocic\GoogleAuthenticator\Secret->setValue('JVIVET2MKBJUEU2...') #1  {FOLDER}/system/external/jocic/google-authenticator/source/Jocic/GoogleAuthenticator/Account.php(339): Jocic\GoogleAuthenticator\Secret->__construct('JVIVET2MKBJUEU2...') #2 {FOLDER}/system/external/jocic/google-authenticator/source/Jocic/GoogleAuthenticator/Account.php(128): Jocic\GoogleAuthenticator\Account->setAccountSecret('JVIVET2MKBJUEU2...') #3 {FOLDER}/system/datastore/n1cqm5613748d7246cp9v9ykuumg5p1b/999999999/2fa/variables.php(34): Jocic\GoogleAuthenticator\Account->__construct('Example', 'example@cwinfo....', 'JVIVET2MKBJUEU2 in {FOLDER}/system/external/jocic/google-authenticator/source/Jocic/GoogleAuthenticator/Secret.php on line 194

**Comment by cwchristerw** [comment]
This is because in Secret.php there is this             
if (count($characters) != 16)
{
    return false;
}

**Comment by cwchristerw** [comment]
Temporary fixed by commenting out length check in Secret.php
```php
            // Step 1 - Check Length
            
            /*
            if (count($characters) != 16)
            {
                return false;
            }
            */
```

**Comment by jocic** [comment]
Thank you for reporting the issue, I will resolve it as soon as possible!

**Comment by amjithps** [comment]
Is this issue solved?

**Comment by jocic** [comment]
Yes, issue has been resolved.
